apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "debian9"
  labels:
    app: containerized-data-importer
  annotations:
    kubevirt.io/provisionOnNode: kubevirt-demo2
    cdi.kubevirt.io/storage.import.endpoint: "http://192.168.0.9/debian-9.13.19-20210320-openstack-amd64.qcow2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: kubevirt-hostpath-provisioner
