apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "rhel8"
  labels:
    app: containerized-data-importer
  annotations:
    kubevirt.io/provisionOnNode: kubevirt-demo2
    cdi.kubevirt.io/storage.import.endpoint: "http://192.168.0.9/rhel-8.3-update-2-x86_64-kvm.qcow2"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: kubevirt-hostpath-provisioner
