apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "ubuntu-focal"
  labels:
    app: containerized-data-importer
  annotations:
    kubevirt.io/provisionOnNode: kubevirt-demo2
    # Use This Image: https://cloud-images.ubuntu.com/focal/
    cdi.kubevirt.io/storage.import.endpoint: "http://192.168.0.9/focal-server-cloudimg-amd64.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: kubevirt-hostpath-provisioner
